# -*- coding: utf-8 -*-
"""assignment1_jo0406.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxpKnfs__HjCtApm2cwvsG4QvrJfec4d
"""

print ("Hello, World!")